<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;

class PageSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->pages() as $page) {
            Page::query()->updateOrCreate(
                ['slug' => $page['slug']],
                $page,
            );
        }
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function pages(): array
    {
        return [
            [
                'slug' => 'layout',
                'name' => 'Rodapé e chamada',
                'title' => 'Wecomp',
                'meta_description' => 'Engenharia de segurança e conformidade legal para operações em Angola.',
                'data' => [
                    'cta_title' => 'Vamos avaliar os riscos da sua operação.',
                    'cta_text' => 'Consultoria com engenharia HIRA. Primeiro o diagnóstico, depois a proposta.',
                    'cta_button' => 'Pedir consultoria estratégica',
                    'header_cta' => 'Pedir consultoria',
                    'footer_text' => 'Engenharia de segurança e conformidade legal para o crescimento do seu negócio.',
                    'footer_legal' => 'DP 227/19 · DP 195/11 · LGT 12/23 · NP 4386:2014',
                    'copyright' => 'Wecomp. Todos os direitos reservados.',
                ],
            ],
            [
                'slug' => 'home',
                'name' => 'Início',
                'title' => 'Wecomp, engenharia de segurança e conformidade legal',
                'meta_description' => 'Engenharia de riscos, segurança contra incêndios, segurança eletrónica e SHST em conformidade com a legislação angolana.',
                'data' => [
                    'hero_image' => 'hero-home.jpg',
                    'hero_title' => 'Segurança que aguenta o escrutínio legal e o dia a dia da operação.',
                    'hero_text' => 'Engenharia de riscos e conformidade com a legislação angolana. Incêndio, segurança eletrónica e SHST para operações que não podem parar.',
                    'primary_cta' => 'Pedir consultoria',
                    'secondary_cta' => 'Conhecer as soluções',
                    'stats' => [
                        ['number' => '100+', 'label' => 'Pontos operacionais'],
                        ['number' => '21', 'label' => 'Províncias e municípios'],
                        ['number' => '4', 'label' => 'Instituições bancárias'],
                        ['number' => '30+', 'label' => 'Empresas de referência'],
                    ],
                    'problem_kicker' => 'O problema',
                    'problem_title' => 'Em Angola, falhar a conformidade custa mais do que o equipamento.',
                    'problem_text' => 'Três riscos que aparecem repetidamente nas operações que auditamos, e que raramente estão no orçamento inicial.',
                    'risks' => [
                        ['number' => 'RISCO 01', 'title' => 'Sanção e interdição', 'text' => 'Instalações sem projeto conforme o Decreto Presidencial 195/11 ficam expostas a coimas, embargos e recusa de licenciamento.'],
                        ['number' => 'RISCO 02', 'title' => 'Paragem operacional', 'text' => 'Uma agência fechada, uma loja evacuada ou uma linha parada custa receita por hora. Sistemas mal dimensionados falham quando são necessários.'],
                        ['number' => 'RISCO 03', 'title' => 'Responsabilidade laboral', 'text' => 'A Lei Geral do Trabalho 12/23 responsabiliza o empregador pelas condições de SHST e pela documentação dos EPIs.'],
                    ],
                    'solutions_kicker' => '01. Escolha por necessidade',
                    'solutions_title' => 'Três frentes de engenharia, um único sistema de segurança.',
                    'solutions_text' => 'Cada solução tem um enquadramento legal e um processo próprio. Não vendemos equipamento isolado.',
                    'solutions_cta' => 'Ver solução',
                    'method_kicker' => '02. Metodologia',
                    'method_title' => 'Primeiro medimos o risco. Só depois falamos de equipamento.',
                    'method_text' => 'HIRA é uma análise técnica do local antes de qualquer proposta comercial. É o que separa um projeto de segurança de uma lista de compras.',
                    'method_image' => 'metodologia-hira.jpg',
                    'method_caption' => 'Levantamento HIRA em ambiente industrial',
                    'method_cta' => 'Como trabalhamos',
                    'method_items' => [
                        ['text' => 'Levantamento presencial das instalações e processos críticos'],
                        ['text' => 'Classificação por probabilidade e severidade'],
                        ['text' => 'Confronto com o decreto e a norma aplicáveis'],
                        ['text' => 'Prioridade de investimento onde o risco é maior'],
                    ],
                    'coverage_kicker' => '03. Presença nacional',
                    'coverage_title' => 'Do Luanda Sul à Lunda Norte, com a mesma equipa técnica.',
                    'coverage_text' => 'Capilaridade significa menor tempo de resposta e capacidade para executar projetos multi-província com o mesmo caderno de encargos.',
                    'coverage_image' => 'cobertura-nacional.jpg',
                    'coverage_cta' => 'Explorar cobertura completa',
                    'about_kicker' => '04. Sobre nós',
                    'about_title' => 'A conformidade legal é o trabalho, não um selo no catálogo.',
                    'about_text' => 'Tratamos a segurança como continuidade da operação, não só como um centro de custo.',
                    'about_image' => 'sobre-equipa.jpg',
                    'about_caption' => 'Acompanhamento técnico em instalação',
                    'about_points' => [
                        ['title' => 'Especialização em conformidade angolana', 'text' => 'Domínio dos Decretos 227/19 e 195/11 e da Lei Geral do Trabalho 12/23.'],
                        ['title' => 'Metodologia HIRA', 'text' => 'Avaliação de riscos antes de qualquer implementação ou aquisição.'],
                        ['title' => 'Soluções integradas', 'text' => 'Incêndio, SHST e segurança eletrónica a comunicar em conjunto.'],
                        ['title' => 'Experiência em setores exigentes', 'text' => 'Metodologia aplicada em banca, indústria, logística e retalho.'],
                    ],
                ],
            ],
            [
                'slug' => 'about',
                'name' => 'Sobre nós',
                'title' => 'Sobre a Wecomp',
                'meta_description' => 'Conheça a Wecomp, a metodologia de engenharia de riscos e o trabalho de conformidade legal em Angola.',
                'data' => [
                    'hero_kicker' => 'Sobre a Wecomp',
                    'hero_title' => 'Conformidade legal ao serviço da continuidade da operação.',
                    'hero_text' => 'Uma equipa guiada pela engenharia de riscos, pela legislação angolana e pela capacidade de executar em todo o país.',
                    'hero_image' => 'sobre-equipa.jpg',
                    'who_kicker' => 'Quem somos',
                    'who_title' => 'Segurança com método, documentação e responsabilidade.',
                    'who_text' => 'A Wecomp desenvolve soluções integradas de segurança contra incêndios, segurança eletrónica e SHST. Começamos pela realidade da operação e pelo risco, não pelo catálogo de equipamentos.',
                    'who_text_2' => 'Da avaliação HIRA ao comissionamento, cada etapa procura proteger pessoas, património, reputação e continuidade do negócio.',
                    'who_image' => 'metodologia-hira.jpg',
                    'who_caption' => 'Engenharia aplicada no terreno',
                    'values' => [
                        ['title' => 'Missão', 'text' => 'Proteger pessoas, património e operações através de soluções de segurança tecnicamente rigorosas e legalmente sustentadas.'],
                        ['title' => 'Visão', 'text' => 'Ser uma referência angolana em engenharia de segurança, reconhecida pela capacidade técnica e pela execução consistente.'],
                        ['title' => 'Valores', 'text' => 'Rigor técnico, responsabilidade, transparência, prevenção e compromisso com a continuidade do cliente.'],
                    ],
                    'process_kicker' => 'Como trabalhamos',
                    'process_title' => 'Uma decisão técnica deve ficar documentada.',
                    'process_text' => 'O processo reduz improvisação, ajuda a justificar prioridades e deixa documentação útil em auditorias e vistorias.',
                    'process_steps' => [
                        ['number' => '01', 'title' => 'Diagnóstico', 'text' => 'Levantamento das instalações, processos e ativos críticos.'],
                        ['number' => '02', 'title' => 'Avaliação', 'text' => 'Classificação dos riscos por probabilidade e severidade.'],
                        ['number' => '03', 'title' => 'Intervenção', 'text' => 'Projeto e execução conforme a prioridade identificada.'],
                        ['number' => '04', 'title' => 'Evidência', 'text' => 'Testes, formação, documentação e acompanhamento.'],
                    ],
                    'team_kicker' => 'Equipa e certificações',
                    'team_title' => 'A credibilidade técnica pede nomes e provas que se possam verificar.',
                    'team_text' => 'Os perfis dos responsáveis técnicos, as licenças e as certificações serão publicados depois da Wecomp validar a documentação. Até lá, não apresentamos credenciais por confirmar.',
                ],
            ],
            [
                'slug' => 'results',
                'name' => 'Resultados',
                'title' => 'Resultados e cobertura. Wecomp',
                'meta_description' => 'Presença da Wecomp em mais de 100 pontos operacionais, 21 províncias e municípios e diferentes setores em Angola.',
                'data' => [
                    'hero_kicker' => 'Resultados e cobertura',
                    'hero_title' => 'Capacidade técnica em operações espalhadas pelo país.',
                    'hero_text' => 'Mais de 100 pontos operacionais em 21 províncias e municípios, incluindo redes bancárias e projetos em várias localizações.',
                    'hero_image' => 'cobertura-nacional.jpg',
                    'stats' => [
                        ['number' => '100+', 'label' => 'Pontos operacionais'],
                        ['number' => '21', 'label' => 'Províncias e municípios'],
                        ['number' => '4', 'label' => 'Instituições bancárias'],
                        ['number' => '30+', 'label' => 'Empresas de referência'],
                    ],
                    'coverage_kicker' => 'Presença nacional',
                    'coverage_title' => 'Cobertura significa capacidade de resposta. Não é um mapa para impressionar.',
                    'coverage_text' => 'Equipas que conhecem as regiões e um caderno técnico comum ajudam a manter o mesmo critério em operações longe umas das outras.',
                    'locations' => [
                        ['place' => 'Luanda', 'sector' => 'banca', 'label' => 'Banca e operações corporativas'],
                        ['place' => 'Benguela', 'sector' => 'retalho', 'label' => 'Retalho e distribuição'],
                        ['place' => 'Huambo', 'sector' => 'banca', 'label' => 'Rede bancária'],
                        ['place' => 'Cabinda', 'sector' => 'industria', 'label' => 'Indústria e logística'],
                        ['place' => 'Lunda Norte', 'sector' => 'banca', 'label' => 'Rede bancária'],
                        ['place' => 'Huíla', 'sector' => 'retalho', 'label' => 'Retalho e serviços'],
                        ['place' => 'Malanje', 'sector' => 'banca', 'label' => 'Rede bancária'],
                        ['place' => 'Cuanza Sul', 'sector' => 'industria', 'label' => 'Indústria e saúde'],
                        ['place' => 'Bié', 'sector' => 'retalho', 'label' => 'Distribuição'],
                    ],
                    'cases_kicker' => 'Casos de referência',
                    'cases_title' => 'Primeiro os resultados. Os logótipos vêm depois, quando o cliente autorizar.',
                    'cases_text' => 'Os estudos de caso serão publicados quando o problema, a intervenção e o resultado estiverem confirmados pelo cliente.',
                    'cases_notice_title' => 'Conteúdo em validação',
                    'cases_notice_text' => 'Este espaço existe para casos reais. Enquanto não houver números confirmados, não os inventamos.',
                ],
            ],
            [
                'slug' => 'contact',
                'name' => 'Contacto',
                'title' => 'Pedir consultoria. Wecomp',
                'meta_description' => 'Solicite uma avaliação de riscos e conformidade para a sua operação.',
                'data' => [
                    'hero_kicker' => 'Contacto',
                    'hero_title' => 'Vamos avaliar os riscos da sua operação.',
                    'hero_text' => 'Conte-nos o contexto da empresa. A primeira conversa serve para perceber prioridades e âmbito.',
                    'hero_image' => 'contacto-consultoria.jpg',
                    'submit_label' => 'Enviar pedido de consultoria',
                    'success_message' => 'Recebemos o seu pedido. A nossa equipa entrará em contacto.',
                    'address_kicker' => 'Contacto direto',
                    'address' => "Viana, Luanda Sul\nRua da Vila, frente ao Hotel de Pedras",
                    'next_kicker' => 'O que acontece depois?',
                    'next_steps' => [
                        ['text' => 'Enquadramos o setor e a necessidade.'],
                        ['text' => 'Marcamos a primeira conversa técnica.'],
                        ['text' => 'Definimos o âmbito do levantamento HIRA.'],
                    ],
                ],
            ],
            [
                'slug' => 'solutions',
                'name' => 'Soluções, textos da página',
                'title' => 'Soluções de segurança. Wecomp',
                'meta_description' => 'Segurança contra incêndios, segurança eletrónica e SHST integradas a partir de uma avaliação real do risco.',
                'data' => [
                    'hero_kicker' => 'Soluções integradas',
                    'hero_title' => 'Engenharia de segurança desenhada a partir do risco.',
                    'hero_text' => 'Três frentes técnicas que trabalham em conjunto: prevenção, deteção e proteção das pessoas e da operação.',
                    'hero_image' => 'solucoes-integradas.jpg',
                    'hero_cta' => 'Explorar soluções',
                    'list_kicker' => 'Da avaliação à manutenção',
                    'list_title' => 'Não instalamos equipamentos soltos. Projetamos sistemas.',
                    'list_text' => 'Cada solução começa pela identificação de perigos, é dimensionada segundo a lei aplicável e termina com uma entrega documentada.',
                    'empty_text' => 'As soluções estão a ser preparadas para publicação.',
                    'card_cta' => 'Conhecer a solução',
                    'method_kicker' => 'Metodologia comum',
                    'method_title' => 'Quatro fases para passar do risco ao controlo.',
                    'method_steps' => [
                        ['number' => '01', 'title' => 'Diagnóstico HIRA', 'text' => 'Identificamos perigos, vulnerabilidades e ativos críticos.'],
                        ['number' => '02', 'title' => 'Projeto', 'text' => 'Dimensionamos a solução e o enquadramento legal.'],
                        ['number' => '03', 'title' => 'Implementação', 'text' => 'Instalamos, integramos e testamos cada componente.'],
                        ['number' => '04', 'title' => 'Continuidade', 'text' => 'Documentamos, formamos e planeamos a manutenção.'],
                    ],
                    'show_kicker' => 'O problema de negócio',
                    'legal_kicker' => 'Enquadramento legal',
                    'legal_fallback' => 'Legislação aplicável ao projeto',
                    'legal_text' => 'O enquadramento final depende da atividade, da ocupação, do risco e das características das instalações.',
                    'process_kicker' => 'Processo de implementação',
                    'process_title' => 'Da inspeção inicial à operação documentada.',
                    'process_steps' => [
                        ['number' => '01', 'title' => 'Levantamento', 'text' => 'Visita técnica, inventário de ativos e identificação de riscos.'],
                        ['number' => '02', 'title' => 'Dimensionamento', 'text' => 'Projeto, especificação e prioridade de intervenção.'],
                        ['number' => '03', 'title' => 'Execução', 'text' => 'Instalação, integração e controlo de qualidade.'],
                        ['number' => '04', 'title' => 'Comissionamento', 'text' => 'Testes, formação, documentação e plano de manutenção.'],
                    ],
                    'related_kicker' => 'Aplicação por setor',
                    'related_title' => 'Onde esta solução gera maior impacto.',
                    'related_cta' => 'Ver aplicação',
                    'cta_label' => 'Solicitar avaliação HIRA',
                    'details_cta' => 'Conhecer a solução',
                ],
            ],
            [
                'slug' => 'sectors',
                'name' => 'Setores, textos da página',
                'title' => 'Setores. Wecomp',
                'meta_description' => 'Soluções de segurança e conformidade adaptadas à banca, retalho, indústria, logística e saúde.',
                'data' => [
                    'hero_kicker' => 'Setores',
                    'hero_title' => 'Segurança adaptada ao risco de cada operação.',
                    'hero_text' => 'A lei pode ser a mesma. A exposição, a continuidade e a urgência da resposta mudam de setor para setor.',
                    'hero_image' => 'setor-industria.jpg',
                    'list_kicker' => 'Escolha por setor',
                    'list_title' => 'O setor muda. O rigor técnico mantém-se.',
                    'list_text' => 'Cruzamos a operação, as obrigações legais e a solução técnica para chegar a uma resposta que faça sentido.',
                    'empty_text' => 'Os setores estão a ser preparados para publicação.',
                    'card_cta' => 'Explorar setor',
                    'close_kicker' => 'A decisão segue o risco',
                    'close_title' => 'A mesma tecnologia resolve problemas diferentes.',
                    'close_text' => 'Num banco, o foco é a continuidade da agência. No retalho, o fluxo do público. Na indústria, a proteção do trabalhador e dos processos críticos.',
                    'show_kicker' => 'Solução por setor',
                    'show_cta' => 'Falar com um consultor',
                    'context_kicker' => 'Contexto operacional',
                    'approach_kicker' => 'Abordagem Wecomp',
                    'approach_title' => 'Avaliar antes de especificar.',
                    'approach_text' => 'O levantamento olha para a ocupação, os ativos críticos, as pessoas, a continuidade e a lei aplicável.',
                    'related_kicker' => 'Soluções recomendadas',
                    'related_title' => 'Proteção integrada para este setor.',
                    'related_cta' => 'Ver solução',
                    'criteria_kicker' => 'Critérios de projeto',
                    'criteria_title' => 'Quatro dimensões que orientam a intervenção.',
                    'criteria' => [
                        ['text' => 'Pessoas e ocupação'],
                        ['text' => 'Ativos críticos'],
                        ['text' => 'Continuidade operacional'],
                        ['text' => 'Evidência para auditoria'],
                    ],
                ],
            ],
            [
                'slug' => 'privacy',
                'name' => 'Política de privacidade',
                'title' => 'Política de Privacidade. Wecomp',
                'meta_description' => 'Como recolhemos, utilizamos e protegemos os dados enviados através do website.',
                'data' => [
                    'hero_kicker' => 'Informação legal',
                    'hero_image' => 'solucoes-integradas.jpg',
                    'notice' => 'Este texto é uma base de trabalho e ainda precisa de revisão jurídica antes da versão definitiva.',
                    'body' => '<h2>Dados recolhidos</h2><p>O formulário de consultoria recolhe nome, empresa, setor, telefone, email e mensagem para permitir o encaminhamento comercial e a resposta ao pedido.</p><h2>Finalidade e fundamento</h2><p>Os dados são tratados para responder ao contacto solicitado, preparar uma eventual proposta e manter o histórico necessário ao acompanhamento comercial.</p><ul><li>Resposta a pedidos de informação e consultoria</li><li>Comunicação relacionada com o pedido</li><li>Segurança, prevenção de abuso e cumprimento legal</li></ul><h2>Conservação e acesso</h2><p>O acesso deve limitar-se às pessoas da Wecomp que necessitam dos dados para acompanhar o pedido. Os prazos de conservação serão definidos na versão jurídica final.</p><h2>Direitos do titular</h2><p>O titular pode solicitar acesso, correção ou eliminação dos seus dados através dos contactos oficiais da Wecomp, sujeito às obrigações legais aplicáveis.</p>',
                ],
            ],
            [
                'slug' => 'terms',
                'name' => 'Termos de utilização',
                'title' => 'Termos de Utilização. Wecomp',
                'meta_description' => 'Condições aplicáveis ao acesso e utilização do website institucional da Wecomp.',
                'data' => [
                    'hero_kicker' => 'Informação legal',
                    'hero_image' => 'solucoes-integradas.jpg',
                    'notice' => 'Este texto é uma base de trabalho e ainda precisa de revisão jurídica antes da versão definitiva.',
                    'body' => '<h2>Natureza da informação</h2><p>O conteúdo deste website tem natureza institucional e informativa. Não substitui uma avaliação técnica, projeto, parecer legal ou proposta comercial.</p><h2>Pedidos de consultoria</h2><p>O envio de um formulário não constitui adjudicação, contrato ou garantia de execução. O âmbito e as condições são definidos após análise do pedido.</p><h2>Propriedade intelectual</h2><p>Textos, identidade visual, fotografias e materiais técnicos pertencem à Wecomp ou são utilizados com autorização. A reprodução depende de autorização prévia.</p><h2>Limitação de responsabilidade</h2><p>A Wecomp procura manter a informação atualizada, mas o enquadramento técnico e legal deve ser confirmado para cada instalação e contexto operacional.</p>',
                ],
            ],
        ];
    }
}
